version: '3'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: leo
      DB_NAME: issue
      DB_PASS: 123
      DB_PORT: 5432
      JWT_SECRET: coolstory
  postgres:
    image: postgres:10.12-alpine
    volumes:
      - "dbdata:/var/lib/postgres/data"
    ports:
      - 5432:5432/tc
    environment:
      POSTGRES_USER: leo
      POSTGRES_DB: issue
      POSTGRES_PASSWORD: 123
volumes:
  dbdata: